version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: "Dockerfile.dev"
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - WDS_SOCKET_PORT=0
  api:
    build:
      context: ./server
      dockerfile: "Dockerfile.dev"
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=fibUSER
      - PGDATABASE=fibDB
      - PGPASSWORD=mysecretpassword
    volumes:
      - /app/node_modules
      - ./server:/app
  worker:
    build:
      context: ./worker
      dockerfile: "Dockerfile.dev"
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    volumes:
      - /app/node_modules
      - ./worker:/app
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: "Dockerfile.dev"
    ports:
      - 8080:80
  redis:
    image: redis
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=fibUSER
      - POSTGRES_DB=fibDB
      - POSTGRES_PASSWORD=mysecretpassword
