name: Build and deploy

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build client dev container
        run: docker build -t ${{ secrets.DOCKER_ID }}/complex-client-dev -f ./client/Dockerfile.dev ./client/
      
      - name: Run client unit tests
        run: docker run -e CI=true ${{ secrets.DOCKER_ID }}/complex-client-dev npm test

      - name: Build client production
        run: docker build -t ${{ secrets.DOCKER_ID }}/complex-client-prod ./client
 
      - name: Build server production
        run: docker build -t ${{ secrets.DOCKER_ID }}/complex-server-prod ./server
      
      - name: Build nginx production
        run: docker build -t ${{ secrets.DOCKER_ID }}/complex-nginx-prod ./nginx
      
      - name: Build worker production
        run: docker build -t ${{ secrets.DOCKER_ID }}/complex-worker-prod ./worker

      - name: Push client on Docker Hub
        run: docker push ${{ secrets.DOCKER_ID }}/complex-client-prod
      
      - name: Push server on Docker Hub
        run: docker push ${{ secrets.DOCKER_ID }}/complex-server-prod
      
      - name: Push nginx on Docker Hub
        run: docker push ${{ secrets.DOCKER_ID }}/complex-nginx-prod
      
      - name: Push worker on Docker Hub
        run: docker push ${{ secrets.DOCKER_ID }}/complex-worker-prod
