name: Build and deploy

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - 
        name: Build client dev container
        run: docker build -t sbosse233/complex-client-dev -f ./client/Dockerfile.dev ./client/
      
      - 
        name: Run client unit tests
        run: docker run -e CI=true sbosse233/complex-client-dev npm test

      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push client production
        uses: docker/build-push-action@v3
        with:
          context: ./client
          push: true
          tags: sbosse233/complex-client:latest

      -
        name: Build and push server production
        uses: docker/build-push-action@v3
        with:
          context: ./server
          push: true
          tags: sbosse233/complex-server:latest

      -
        name: Build and push nginx production
        uses: docker/build-push-action@v3
        with:
          context: ./nginx
          push: true
          tags: sbosse233/complex-nginx:latest

      -
        name: Build and push worker production
        uses: docker/build-push-action@v3
        with:
          context: ./worker
          push: true
          tags: sbosse233/complex-worker:latest

      - 
        name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      
      - 
        name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: complex-app-udemy
          environment_name: Complexappudemy-env
          existing_bucket_name: 	elasticbeanstalk-us-east-1-728210958726
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip